version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    restart: always 
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=ecommerce" 
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    restart: always 
